spring:
  datasource:
    sqlScriptEncoding: UTF-8
    driverClassName: org.h2.Driver
    url : jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url : jdbc:h2:file:/temp/testdb
    username: sa
    password :
    
    